//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.Employees = new HashSet<Employee>();
            this.Invoices = new HashSet<Invoice>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
        }
    
        public string branch { get; set; }
        public string region { get; set; }
        public string building_name { get; set; }
        public Nullable<int> unit_num { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
    }
}
